---

- name: Disable swap
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap '
    state: absent

- name: Swap Off
  command: swapoff --all
  ignore_errors: yes

- name: Add Kubernetes CentOS7 yum repo
  yum_repository:
    name: kubernetes
    description: Kubernetes Yum Repo
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
    gpgcheck: no    
    state: present

- name: Install Kubernetes basics
  yum: name="{{item}}" state=installed
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni
    - ebtables
    - ethtool

