---

- include: centos-docker.yml
  when: ansible_os_family == 'RedHat' 

- include: centos-kubernetes.yml
  when: ansible_os_family == 'RedHat'

- name: Disable firewalld
  systemd: name="firewalld" enabled=no state=stopped
  with_items:
    - firewalld
  when: ansible_os_family == 'RedHat'

- name: Enable systemd components for Kubernetes
  systemd: name="{{item}}" enabled=yes state=started
  with_items:
    - docker
    - kubelet
  when: ansible_os_family == 'RedHat'

